### ISSUE TITLE
Only for integration testing?

### ISSUE THREAD

**Issue by Rafaesp** [fmonniot/embedded-redis#8]
Hi, would this project be enough for a simple use case using Redis on production?
My idea was to be able to start/stop redis without having to install a separate Redis so the packaging of my app is simpler. 
Do you know any problem that could happen?
Thanks.

**Comment by fmonniot** [comment]
Hi,

This library doesn't come with any guarantee the redis process won't crash.

If that would happens, then I'm not too sure as to how you could get back your data (maybe scan the temporary folders to find the good one, or retro-engineer the lib to find where they have been put). Also if it crash, there is no watcher on it and it wouldn't be auto-restart.

If you have the choice, I'll say go with a docker container orchestrated from your app. Otherwise, feel free to fork this project and add the missing features you need :)

**Comment by Rafaesp** [comment]
Thanks a lot!

**Comment by fmonniot** [comment]
You're welcome :grinning:
